/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#303030",
        "tertiary-fixed-dim": "#474747",
        "on-primary-fixed": "#ffffff",
        "on-tertiary-container": "#000000",
        "on-surface-variant": "#c6c6c6",
        "on-background": "#e2e2e2",
        "on-tertiary": "#1b1b1b",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#3a3c3c",
        "inverse-primary": "#5d5f5f",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#5d5f5f",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#e2e2e2",
        "tertiary": "#e2e2e2",
        "outline-variant": "#474747",
        "surface-container": "#1f1f1f",
        "on-surface": "#e2e2e2",
        "surface-container-highest": "#353535",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "tertiary-fixed": "#5e5e5e",
        "secondary-container": "#464747",
        "surface-container-low": "#1b1b1b",
        "on-primary-container": "#000000",
        "on-primary": "#1a1c1c",
        "surface-bright": "#393939",
        "on-error-container": "#ffdad6",
        "surface-tint": "#c6c6c7",
        "on-tertiary-fixed": "#ffffff",
        "tertiary-container": "#919191",
        "surface-variant": "#353535",
        "on-secondary": "#1a1c1c",
        "background": "#131313",
        "inverse-surface": "#e2e2e2",
        "surface": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "primary-fixed-dim": "#454747",
        "primary": "#ffffff",
        "secondary-fixed-dim": "#ababab",
        "secondary": "#c7c6c6",
        "secondary-fixed": "#c7c6c6",
        "outline": "#919191",
        "on-secondary-container": "#e3e2e2",
        "on-error": "#690005",
        "surface-dim": "#131313",
        "primary-container": "#d4d4d4",
        "error-container": "#93000a",
        "accent-purple": "#A855F7"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('tailwindcss-animate'),
  ],
}
